Fix typos
vmware-labs/wasm-workers-server pull request #14
Opened 2022-10-19 16:50 UTC by ssssota

Very interesting project!

Fixed typo in the documents.

2022-10-19 19:13 UTC, ereslibre requested changes
Thank you @ssssota! A couple of suggestions. Once that the license agreement is accepted we can merge your fixes!

2022-10-19 19:13 UTC, ereslibre commented on docs/docs/intro.md
> +Wasm Workers Server is a project that allows you to run serverless code using a lightweight construct called "workers", explained later in the document. There server itself is implemented as a self-c
```suggestion
Wasm Workers Server is a project that allows you to run serverless code using a lightweight construct called "workers", explained later in the document. The server itself is implemented as a self-contained binary that routes HTTP requests to a WebAssembly runtime that hosts the workers. It looks for `.wasm` and other compatible modules (like JavaScript files) in the given folder and associate HTTP endpoints based on their path:
```

2022-10-19 19:13 UTC, ereslibre commented on docs/docs/intro.md
> +Many of the platforms mentioned earlier follow a similar approach, so any code you write for Wasm Workers Server can be moved to those platforms easily (or the other way around!). Remember that our f
I think we can remove this from the patch, I cannot see any difference.

2022-10-20 00:34 UTC, ssssota commented on docs/docs/intro.md
> +Many of the platforms mentioned earlier follow a similar approach, so any code you write for Wasm Workers Server can be moved to those platforms easily (or the other way around!). Remember that our f
I checked locally and found that line breaks were added.
I have pushed it again with that correction as well, so please check!

2022-10-25 12:30 UTC, gzurl commented
Thanks @ssssota for your patch!
@ereslibre this LGTM now. But you are the change request owner :-)

2022-10-25 12:31 UTC, gzurl approved these changes
LGTM!

2022-10-25 19:20 UTC, ereslibre approved these changes

2022-10-25 19:20 UTC, ereslibre commented
Thank you @ssssota!

2022-10-25 19:21 UTC, merged